### ISSUE TITLE
Windows don't get killed when any button is clicked

### ISSUE THREAD

**Issue by JYunth** [JYunth/hotel-management-system#1]

**Comment by UjjwalAggarwal-1** [comment]
what exactly do you mean by this?

i cloned the project, and i ran the main.py, it works fine and the window gets killed upon closing

am i missing something?

**Comment by UjjwalAggarwal-1** [comment]
oh wait, did you mean it does not close when clicking the home button?

**Comment by UjjwalAggarwal-1** [comment]
check out PR #6 , fixed it

**Comment by JYunth** [comment]
Sorry @UjjwalAggarwal-1, I made this issue a long time ago, didn't occur to me that I needed to be elaborate 😅

What I tried to mean is, when you enter the check in page, the homepage doesn't close and it stays in the background

**Comment by UjjwalAggarwal-1** [comment]
Please see to the PR, it has been resolved
pr #6

**Comment by UjjwalAggarwal-1** [comment]
i would like to suggest leaving it in the background. 
people are tend to kill a window than press the home button, and by leaving it there, we ensure he is in the program

**Comment by JYunth** [comment]
Yes, I sort of know what you mean. But this problem affects subsequent menus as well. When you click on the home button in check in menu, it creates another homescreen; so your desktop has 3 windows open, the first homepage, the checkin page, and another homepage.

**Comment by JYunth** [comment]
Since the windows dont get killed, youre left with 14-15 windows open at the same time when you're done using the app, which is a very annoying bug

**Comment by UjjwalAggarwal-1** [comment]
well i fixed that issue
the subsequent windows are closed

**Comment by UjjwalAggarwal-1** [comment]
> Yes, I sort of know what you mean. But this problem affects subsequent menus as well. When you click on the home button in check in menu, it creates another homescreen; so your desktop has 3 windows open, the first homepage, the checkin page, and another homepage.

these "another homescreen" issue has been resolved

**Comment by JYunth** [comment]
Alright, changes have been reviewed and merged. Thank you @UjjwalAggarwal-1
