### ISSUE TITLE
Check Into OceanView title has border while other menus do not

### ISSUE THREAD

**Issue by LeaDevelop** [JYunth/hotel-management-system#10]
To make the titles consistent would remove the border around the Check into Oceanview title.
![2022-10-25 07_54_29-Lea](https://user-images.githubusercontent.com/104503492/197693697-eb084894-42d0-4fcd-965e-af86b704df91.png)
![2022-10-25 07_55_00-Lea](https://user-images.githubusercontent.com/104503492/197693782-88fb7d32-18e2-44e4-af20-2ebbc6209d56.png)
![2022-10-25 07_55_10-Lea](https://user-images.githubusercontent.com/104503492/197693783-af389fce-d6ec-4918-9486-0b79774e9311.png)

I volunteer to resolve the issue.

**Comment by LeaDevelop** [comment]
Ah I see if you mention hash and number it will auto call it here, that's cool :)
And sorry for confusion, seems my IDE has old account still in memory even tho I don't actively use it anymore.
Update: It's not IDE it's Git user name I set years back when I set git for first time xD I updated it accordingly now, so no more confusion from two Lea's :3
Bug fix pushed. Thanks for sharing the repo for others to contribute, it's been fun learning journey <3

**Comment by LeyaSi** [comment]
Ahhh it's not IDE it's Git user I set years ago, I adjusted it now, so no more confusion on the way from two Lea's haha
