### ISSUE TITLE
Enhancement: Increase font size in input fields

### ISSUE THREAD

**Issue by LeaDevelop** [JYunth/hotel-management-system#17]
If we look at current scale of the label font size describing input field and compare it to the font size in the input fields the proportions aren't really close to each other. Would adjust it so the input field font size is at least 14 (at the after screenshot example is set to 14).

Before:
![2022-10-25 22_38_23-Lea](https://user-images.githubusercontent.com/104503492/197877198-c60060fe-5764-4d77-be0c-4fbec4fa7672.png)

After:
![2022-10-25 22_51_13-Lea](https://user-images.githubusercontent.com/104503492/197879537-aa33fa4c-c56b-4d22-bd42-41df1ba61941.png)

If you like the proposal, I'd like to volunteer and take care of it in each frame.

**Comment by JYunth** [comment]
Sounds good. You have been assigned
