### ISSUE TITLE
No window icon for any of the windows

### ISSUE THREAD

**Issue by JYunth** [JYunth/hotel-management-system#2]

**Comment by LeaDevelop** [comment]
You already have icon art?

**Comment by LeaDevelop** [comment]
I can volunteer to prepare few samples in case you don't have already and then also implement.

**Comment by LeaDevelop** [comment]
![example-1](https://user-images.githubusercontent.com/104503492/197609721-74bb6fb3-6998-48c2-a317-5d8d1260e588.png)

**Comment by JYunth** [comment]
This one looks good for now. Maybe in the future I could rebrand everything with a singular logo/theme/UI but that's a milestone far away

**Comment by LeaDevelop** [comment]
Then feel free to assign to me and I'll send a pull request with this placeholder icon :)

**Comment by LeaDevelop** [comment]
Pull request was sent in https://github.com/JYunth/hotel-management-system/pull/11
