### ISSUE TITLE
The room randomizer in check_in_ui.py is a dumpster fire

### ISSUE THREAD

**Issue by JYunth** [JYunth/hotel-management-system#3]

**Comment by JYunth** [comment]
Remove the random room assigner and implement an assigner that assigns customers rooms on a consecutive basis

**Comment by UjjwalAggarwal-1** [comment]
what do you have in mind?

**Comment by JYunth** [comment]
No idea what I had in mind when I first made this issue, I made it really long ago
I guess I'll fix this issue myself later
