### ISSUE TITLE
Check-in error does not reflect what field had wrong number

### ISSUE THREAD

**Issue by LeaDevelop** [JYunth/hotel-management-system#7]
Check-in error does not reflect what field had wrong number
![Error-does-not-state-what-number](https://user-images.githubusercontent.com/104503492/197360493-5b97730b-18fa-405a-ab76-d58554e13028.png)
![CheckIn](https://user-images.githubusercontent.com/104503492/197360491-e4da48d1-3bbf-4d81-9e3b-81a1c53290a2.png)

I volunteer to improve the error message being more specific.

P.S. 
Future enhancement suggestion: Improve UI on Check-In screen, to have tooltips explaining valid values or check for invalid ones there, so check of valid values is done on that screen. That way user does not need to re-enter all entries in case of error.

**Comment by JYunth** [comment]
Thank you for working on this! Here you go, you have been assigned to this issue

Also thanks for the suggestion, will consider it

**Comment by LeaDevelop** [comment]
Pull request created - https://github.com/JYunth/hotel-management-system/pull/9

**Comment by JYunth** [comment]
PR #9 reviewed and merged, thank you very much!
